### PR TITLE
Upgrade to paper_elements 1.0.6 and some more goodies

### PR DESCRIPTION
**Pull request by dam0vm3nt**
Upgraded `paper_elements` to 1.0.6 and the following components causing troubles with FF:
- `paper-header-panel` to 1.1.2
- `paper-dialog-behavior` to 1.1.0
- `paper-dialog` to 1.0.3

Updated tests too.

### CODE REVIEW

**Comment by jakemac53** [comment]
uploaded to reitveld for review https://codereview.chromium.org/1495293002

**Comment by jakemac53** [comment]
ok I just added a few comments on rietveld, really minor everything looks great

**Comment by dam0vm3nt** [comment]
Wonderfull

Il giorno ven 4 dic 2015, 19:22 Jacob MacDonald notifications@github.com
ha scritto:

**Comment by dam0vm3nt** [comment]
For the `iron-image` test suite splitted: I had to do it because otherwise the test was failing. But it seams a problem of the fixture framework rather than of the components

**Comment by jakemac53** [comment]
ah ok, thats fine then

**Comment by jakemac53** [comment]
Oh one more thing, if you can add a CHANGELOG entry mentioning the new `paper-listbox` element and anything else you deem relevant that would be great.

**Comment by dam0vm3nt** [comment]
Ok if you don't mind await for a few hours...

``` dart
UpdatedChangelog x = await haveDinner(me);
```

**Pull request merged**
