### PR TITLE
As promised, my work on updating elements

### PR DESCRIPTION
**Pull request by dam0vm3nt**
There's also a `changed_tests` file I was using to track progress on porting tests.

My intention was to repeat the whole process (updating elements, and fixing test) until it eventually converge to a stable solution (id est in the meanwhile I was going to update the test there are no more commits on the js side). 

Feel free to use this PR in whatever manner you like (merging, copying and pasting, cherrypicking ... whatever).

### CODE REVIEW

**Comment by jakemac53** [comment]
Great thanks, I can take it over from here if that is ok.

**Comment by jakemac53** [comment]
unless you want to continue porting tests?

**Comment by dam0vm3nt** [comment]
I really would like to do it (I'm honest), But I don't think I can spend too much time on it for next 10 days because I'm on a deadline. And I know everybody is waiting for this so probably it is better for you to take it over.

I can tell you that I'm actually using it with latest polymer and it doesn't seams to break anything, but as usual unit tests are the best choice.

**Comment by jakemac53** [comment]
Ok ya in that case I think I will just take it over where it is at now if you don't mind, because this stuff also gets stale really quick. I will keep your commits in place and such tho so you still get the credit for what you have done here ;).

**Comment by dam0vm3nt** [comment]
thanks! I really appreciate it.

**Comment by jakemac53** [comment]
Manually merged after I picked up where you left off

**Pull request closed without merging**
