### PR TITLE
upgrading paper_elements to 1.0.6

### LINKED ISSUE #93: paper_drawer_panel not working on firefox, drawer always closed
In my app, the drawer is always closed. Trying to reproduce it in a simple example below (based on the javascript documentation), the drawer was shown below the main panel in firefox

The same example works fine on Chrome. There was a similar issue in version 1.0.3 of the js version due to a vulcanize issue: https://github.com/PolymerElements/paper-drawer-panel/issues/78. However the javascript version works fine (in the demo page)

``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>paper_drawer_panel_example</title>
    <script src="packages/web_components/webcomponents-lite.min.js"></script>
    <link rel="import" href="packages/polymer_elements/paper_drawer_panel.html">
    <link rel="import" href="packages/polymer_elements/paper_header_panel.html">
    <link rel="import" href="packages/polymer_elements/paper_toolbar.html">
    <link rel="import" href="packages/polymer_elements/iron_icons.html">
    <link rel="import" href="packages/polymer_elements/paper_icon_button.html">
</head>
<body unresolved>
<paper-drawer-panel>
    <paper-header-panel drawer>
        <paper-toolbar>
            <div>Application</div>
        </paper-toolbar>
        <div> Drawer content...</div>
    </paper-header-panel>
    <paper-header-panel main>
        <paper-toolbar>
            <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
            <div>Title</div>
        </paper-toolbar>
        <div> Main content...</div>
    </paper-header-panel>
</paper-drawer-panel>
<script type="application/dart" src="paper_drawer_panel_example.dart"></script>
<script src="packages/browser/dart.js"></script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by dam0vm3nt**
This should fix #93 even though there are still problems with `paper-dialog`.

### CODE REVIEW

**Comment by jakemac53** [comment]
As a part of the upgrade we also need to update the tests. Are you willing to do that or should we merge this into a separate branch and then I can work on doing it?

**Comment by jakemac53** [comment]
Also I am not sure if you have used reitveld before, but for reviews of this size that is typically what we use just because it can handle unlimited numbers of files. That is not a requirement (I can just review the changes locally) but if you already have it set up that would be great.

**Comment by dam0vm3nt** [comment]
I can update the test, but I'm not sure I understand what this actually means (e.g. : adding tests for new elements ?).

Never used reitveld, sorry, but it sounds interesting I'll check it. 

But if this can help reviewing basically I've only updated the version of `paper_elements` in `bower.json`, added  generation of `polymer_spinner_style.dart` in `polymer_elements_config.yaml` and run the `custom_element_apigen` tool. The big changes are due to the `paper_element` updates from JS.

**Comment by jakemac53** [comment]
> I can update the test, but I'm not sure I understand what this actually means (e.g. : adding tests for new elements ?).

We have ported all the js tests to dart, and so we want to maintain those. Basically you just look at the diffs for each of the js tests, and then go apply those same changes to the dart tests.

> Never used reitveld, sorry, but it sounds interesting I'll check it.

https://github.com/dart-lang/sdk/wiki/Code-review-workflow-with-GitHub-and-reitveld is some docs on this, but its a bit of work to get it all set up. If you have some other app locally that you use to view diffs then that might be easier :).

> But if this can help reviewing basically I've only updated the version of paper_elements in bower.json, added generation of polymer_spinner_style.dart in polymer_elements_config.yaml and run the custom_element_apigen tool. The big changes are due to the paper_element updates from JS.

I still have to actually look over the changes just to make sure haha :)

**Comment by dam0vm3nt** [comment]
ok, I'm going to port tests too and I'll take a look at reitveld. 

In the meanwhile do you have an idea why `polymer-dart` is not working well (on firefox/safari) with external imported stylesheets? (I think that is the actual cause of #93 ), see [here](https://github.com/dart-lang/polymer_elements/issues/93#issuecomment-156446397) for more info.

**Comment by jakemac53** [comment]
I think the issue is that the web_components transformer specifically skips them (on purpose). This was done to prevent duplicate styles getting inlined in multiple elements (the typical reason for using an external stylesheet is if its shared).

Luckily these are already deprecated anyways, so I don't have any plans currently to try and actually address the issue and figure out why not inlining them is causing issues in FF. The elements should start migrating off of them soon.

**Comment by dam0vm3nt** [comment]
OK, good to know this. So basically we just have to wait for elements to update. 

Maybe then it is better to wait for them and abort this upgrade ?

**Comment by jakemac53** [comment]
Well some of the elements have already moved off of it (like paper-drawer-panel) so it definitely has value, its up to you. Also generally updating the elements is always good.

**Comment by dam0vm3nt** [comment]
Ok. Just didn't want to burden you with having to revise something twice. I'll proceed also because I really can't stand that bug anymore :-)

**Comment by dam0vm3nt** [comment]
@jakemac53 I think I've finished porting the tests but I did not succeed in setting up the reitveld workflow (specifically cannot find how to install `git-cl`). Hope this is enough though if you want to take a look at it.

Since there were still problems with `paper-header-panel` and `paper-dialog` styles on FF I have patched 'em in another branch of [mine](https://github.com/dam0vm3nt/polymer_elements/tree/fixy). If you think is worth instead of waiting for polymers to fix 'em let me know and I will PR it.

**Comment by jakemac53** [comment]
I can just pull this down locally and diff it

**Comment by jakemac53** [comment]
Seeing some failing tests, can you look into those?  It uses the regular test runner - `pub run test -pdartium`. The `iron-collapse` test is flaky but the others should succeed.

**Comment by dam0vm3nt** [comment]
Yep I will.

Il giorno lun 16 nov 2015, 21:25 Jacob MacDonald notifications@github.com
ha scritto:

**Comment by dam0vm3nt** [comment]
Fixed some tests but pretty stuck on the remaining. @jakemac53 any hint ?

**Comment by jakemac53** [comment]
Well, it looks like at least for paper-radio-group the original js tests are failing as well :/ [repo](https://github.com/PolymerElements/paper-radio-group), [travis](https://travis-ci.org/PolymerElements/paper-radio-group/jobs/88467377)

**Comment by jakemac53** [comment]
I tried messing around a bit with the paper-radio-group and it looks like possibly some things are happening async that used to be sync, so adding in a few `await wait(0);` calls will likely resolve some of the failing tests.

**Comment by dam0vm3nt** [comment]
added `await wait(0);` and now they work, I'll try to fix the remaining but I fear I will be very slow at it.

**Comment by dam0vm3nt** [comment]
marked transitive test on `iron-a11-keys-behavior` as skipped because original JS test was failing. Maybe upgrade that element to the last version ?

`iron-form` reset of field does not work. I see that `_customElements` get their `value` resetted but that change does not get propagated to `dart` methink ...

what do you think about this @jakemac53 ?

**Pull request merged**
