### PR TITLE
Update 20160616

### PR DESCRIPTION
**Pull request by dam0vm3nt**

### CODE REVIEW

**Comment by dam0vm3nt** [comment]
All tests are currently running ok in dartium. Missing only `app-*` tests.

**Comment by dam0vm3nt** [comment]
hi @jakemac53 , everything should be ready for your review:
- all tests are successfull with dartium 
- changelog updated
- pubspec updated

I had to run tests with `-j 1` otherwise the test runner get confused. Also some tests need the test runner to be _hacked_ : I had to reveal the hidden `iframe` in order for some events to be fired.

Let me know if you need something else.

**Comment by jakemac53** [comment]
Ok thanks, taking a look.

**Comment by jakemac53** [comment]
superseded by pull #132

**Pull request closed without merging**
